version: "3.8"
services:
  db:
    image: postgres
    # image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./data/scripts:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: integration
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
